version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
    overwrite: true
permissions:
  - object: /var/app
    pattern: "**"
    owner: nodejs
    group: nodejs
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root 